import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Mode } from "@/components/asset/Mode";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RC-Layout",
  description: "Generated by RC-Lab",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Mode />
        </ThemeProvider>
      </body>
    </html>
  );
}
